// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    // This message listener waits for a command from the web page to activate.
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "be2d423b934b9c0b01d83184d3d4aa59"
    },
    {
        "url": "icon-96.png",
        "revision": "68bc111c2ddf34ecb0f446c5401b6906"
    },
    {
        "url": "icon-128.png",
        "revision": "190a33883d0b48d87d84cba89ef60d47"
    },
    {
        "url": "icon-144.png",
        "revision": "6a03fe4fafbbe1a7114f808f2c7e447a"
    },
    {
        "url": "icon-152.png",
        "revision": "71f71a48af9554d3087248e67965040f"
    },
    {
        "url": "icon-192.png",
        "revision": "445eafa87e5dae0090d9389487c5d532"
    },
    {
        "url": "icon-384.png",
        "revision": "3b1f7dea813cbec85b21ee8147eb5100"
    },
    {
        "url": "icon-512.png",
        "revision": "3d68d791052605e8692bab71b396a5f8"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates.py",
        "revision": "ce8e62bbacde6a60773ea36bfc4dbb2a"
    },
    {
        "url": "index.html",
        "revision": "b50313c8bc725cf9cbd19c116f0e49d9"
    },
    {
        "url": "manifest.json",
        "revision": "ef4c0b8f133f23abb91ec5bb70d20c94"
    },
    {
        "url": "offline.html",
        "revision": "986de93949013e958b0e14acd85491cd"
    },
    {
        "url": "sw.js",
        "revision": "0f1f236edc89fdef3c9141274ffbdab9"
    },
    {
        "url": "fonts/LhWNMUPbN-oZdNFcBy1-DJYsEoTq5pudQ9L940pGPkB3Qt_-DK0.ttf",
        "revision": "c36c97a3e8b2af5538451cf550693e4a"
    },
    {
        "url": "libs/all.min.css",
        "revision": "ded1c367363e8b20bdc6a19b8350a737"
    },
    {
        "url": "libs/all.min.js",
        "revision": "78cdcbfac5817d1dca139718d1b9a8f5"
    },
    {
        "url": "libs/bootstrap.bundle.min.js",
        "revision": "849e6db145f2905ce210f628bddd9de5"
    },
    {
        "url": "libs/bootstrap.min.css",
        "revision": "fe7fdfec700d100dc745dc64d3600cb2"
    },
    {
        "url": "libs/chart.js",
        "revision": "187ffe7a12d1079ea1653198f9e19187"
    },
    {
        "url": "libs/chart.min.js",
        "revision": "7dd5ea7d2cf22a1c42b43c40093d2669"
    },
    {
        "url": "libs/chartjs-plugin-datalabels.min.js",
        "revision": "474739ea5d80b5c7a578f366c3b05cc6"
    },
    {
        "url": "libs/dom-to-image-more.min.js",
        "revision": "17d1d3d10e7f7e6345fa306d9a06b58a"
    },
    {
        "url": "libs/html2canvas.min.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "libs/jspdf.plugin.autotable.min.js",
        "revision": "49db477f98e9be3054a598a269b36a4e"
    },
    {
        "url": "libs/jspdf.umd.min.js",
        "revision": "4b16d1b6023fa7271c62b3dee913c3ca"
    },
    {
        "url": "libs/logo.jpg",
        "revision": "468c04fa7845a4946699daefb0de9c78"
    },
    {
        "url": "libs/sha256.min.js",
        "revision": "e5a5b331cf54c474203628eb9398470e"
    },
    {
        "url": "libs/sign.png",
        "revision": "e55465b7182574d23097001157fa679d"
    },
    {
        "url": "libs/xlsx.full.min.js",
        "revision": "31e9848e80e1ddf43c5aa31009cd2b7b"
    },
    {
        "url": "webfonts/fa-brands-400.ttf",
        "revision": "513aa607d398efaccc559916c3431403"
    },
    {
        "url": "webfonts/fa-brands-400.woff2",
        "revision": "ed311c7a0ade9a75bb3ebf5a7670f31d"
    },
    {
        "url": "webfonts/fa-regular-400.ttf",
        "revision": "766913e6c0088ab8c9f73e18b4127bc4"
    },
    {
        "url": "webfonts/fa-regular-400.woff2",
        "revision": "b91d376b8d7646d671cd820950d5f7f1"
    },
    {
        "url": "webfonts/fa-solid-900.ttf",
        "revision": "b9625119ce4300f0ef890a8f3234c773"
    },
    {
        "url": "webfonts/fa-solid-900.woff2",
        "revision": "d824df7eb2e268626a2dd9a6a741ac4e"
    },
    {
        "url": "webfonts/fa-v4compatibility.ttf",
        "revision": "8ae3b70674df55c9c994704c30527619"
    },
    {
        "url": "webfonts/fa-v4compatibility.woff2",
        "revision": "36bcf29aafd017d073ca7d17f1b5088d"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}