// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates new.py",
        "revision": "6f204d68894960c2efd7b6379cfbddab"
    },
    {
        "url": "Copy of build pwa make html app offline and installable yasin best working re-run this for updates.py",
        "revision": "ce8e62bbacde6a60773ea36bfc4dbb2a"
    },
    {
        "url": "index.html",
        "revision": "8868b1bd3751bc35098c5e65140ba054"
    },
    {
        "url": "logo.jpg",
        "revision": "468c04fa7845a4946699daefb0de9c78"
    },
    {
        "url": "manifest.json",
        "revision": "ef4c0b8f133f23abb91ec5bb70d20c94"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "sw.js",
        "revision": "187440438f233506251e967c6401a178"
    },
    {
        "url": "fonts/LhWNMUPbN-oZdNFcBy1-DJYsEoTq5pudQ9L940pGPkB3Qt_-DK0.ttf",
        "revision": "c36c97a3e8b2af5538451cf550693e4a"
    },
    {
        "url": "libs/all.min.css",
        "revision": "ded1c367363e8b20bdc6a19b8350a737"
    },
    {
        "url": "libs/all.min.js",
        "revision": "78cdcbfac5817d1dca139718d1b9a8f5"
    },
    {
        "url": "libs/bootstrap.bundle.min.js",
        "revision": "849e6db145f2905ce210f628bddd9de5"
    },
    {
        "url": "libs/bootstrap.min.css",
        "revision": "fe7fdfec700d100dc745dc64d3600cb2"
    },
    {
        "url": "libs/chart.js",
        "revision": "187ffe7a12d1079ea1653198f9e19187"
    },
    {
        "url": "libs/chart.min.js",
        "revision": "7dd5ea7d2cf22a1c42b43c40093d2669"
    },
    {
        "url": "libs/chartjs-plugin-datalabels.min.js",
        "revision": "474739ea5d80b5c7a578f366c3b05cc6"
    },
    {
        "url": "libs/dom-to-image-more.min.js",
        "revision": "17d1d3d10e7f7e6345fa306d9a06b58a"
    },
    {
        "url": "libs/html2canvas.min.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "libs/jspdf.plugin.autotable.min.js",
        "revision": "49db477f98e9be3054a598a269b36a4e"
    },
    {
        "url": "libs/jspdf.umd.min.js",
        "revision": "4b16d1b6023fa7271c62b3dee913c3ca"
    },
    {
        "url": "libs/logo.jpg",
        "revision": "468c04fa7845a4946699daefb0de9c78"
    },
    {
        "url": "libs/sha256.min.js",
        "revision": "e5a5b331cf54c474203628eb9398470e"
    },
    {
        "url": "libs/sign.png",
        "revision": "e55465b7182574d23097001157fa679d"
    },
    {
        "url": "libs/xlsx.full.min.js",
        "revision": "31e9848e80e1ddf43c5aa31009cd2b7b"
    },
    {
        "url": "webfonts/fa-brands-400.ttf",
        "revision": "513aa607d398efaccc559916c3431403"
    },
    {
        "url": "webfonts/fa-brands-400.woff2",
        "revision": "ed311c7a0ade9a75bb3ebf5a7670f31d"
    },
    {
        "url": "webfonts/fa-regular-400.ttf",
        "revision": "766913e6c0088ab8c9f73e18b4127bc4"
    },
    {
        "url": "webfonts/fa-regular-400.woff2",
        "revision": "b91d376b8d7646d671cd820950d5f7f1"
    },
    {
        "url": "webfonts/fa-solid-900.ttf",
        "revision": "b9625119ce4300f0ef890a8f3234c773"
    },
    {
        "url": "webfonts/fa-solid-900.woff2",
        "revision": "d824df7eb2e268626a2dd9a6a741ac4e"
    },
    {
        "url": "webfonts/fa-v4compatibility.ttf",
        "revision": "8ae3b70674df55c9c994704c30527619"
    },
    {
        "url": "webfonts/fa-v4compatibility.woff2",
        "revision": "36bcf29aafd017d073ca7d17f1b5088d"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}